# Generated by Django 2.2.1 on 2019-10-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='作者性别')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('pthone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='文章类型')),
                ('description', models.TextField(verbose_name='类型描述')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章名字')),
                ('date', models.DateField(auto_now=True, verbose_name='文章日期')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('description', models.TextField(verbose_name='文章描述')),
                ('picture', models.ImageField(upload_to='images', verbose_name='图片')),
                ('recommend', models.IntegerField(default=0, verbose_name='推荐')),
                ('click', models.IntegerField(default=0, verbose_name='点击率')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Back.Author', verbose_name='文章作者')),
                ('type', models.ManyToManyField(to='Back.Type')),
            ],
        ),
    ]
