# Generated by Django 2.2.1 on 2019-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_auto_20191007_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
